### ISSUE TITLE
Missing source files

### ISSUE THREAD

**Issue by neslo** [fcancillo/RXtoRINEX-V2.0#1]
Hi  Francisco,

I am trying to build the RXtoOSP on raspberian and the files for SerialTxRx are missing.  Could I get you to add them if you still have them somewhere.

Best Regards,
Thomas

**Comment by fcancillo** [comment]
Sorry Thomas …
I just uploaded to the repository the missing code. Note that the implementation of the SeriaTxRx class is very specific for Windows.
By the way: I have just started to move code to Linux (Ubuntu) environment …

**Comment by neslo** [comment]
Thank you Francisco for adding the missing files.

And great that you are already working on a linux version. That should work on the raspberry pi too.

Any estimate when you have a linux RXtoOSP version ready?

I have got a GlobalSat BU-353-S4 USB GPS Receiver and I have got it working with GPSD but it does not include the subframes (e.g. MID 15) because GPSD turns that off if the baud rate is below 57600 (the BU-353-S4 defaults to 4800 baud). 

So I was hoping that i could force the sub frames with your project.

Which gps have you been testing?

Cheers,
Thomas

**Comment by fcancillo** [comment]
Unfortunately I cannot give you a date for the availability of the Linux version, because I am not full time dedicated to this activity.
The receivers used to collect data in the ./Data directory were the ones described in “Test files” section of the “readme” file.
To collect the GlobalSat data, it was connected to a Toshiba Tecra with Windows 7. I used first the command SynchroRX.exe to set and synchronize rx and tx speeds at receiver and PC ports, and then RXtoOSP.exe to receive the OSP messages at 57600bps. As you can see in the sample OSP files MID15 messages are present.

**Comment by neslo** [comment]
No worries and know that issue all to well myself.

Thanks heaps for the details and especially the SynchroRX.exe bit. I have located gpsctl which does a similar thing in linux. So i have been able to set the speed to 57600 such that i get the extra messages now via gpsd and gpspipe 

I am however still missing the mid 15 messages because they need to be polled but hope i can still generate something and specify to use mid8 instead.

I noticed that OSPtoRinex.exe is v1.0. Would you be able to replace it with your version 2.0 (if you still have that exe somewhere on your system.)?

**Comment by fcancillo** [comment]
I reviewed the gpsd documentation and my conclusion is that you whould need a filter to translate the what they call binary output from gpscat to the pure OSP format used in the this package (real binary data and start of message stripped from the receiver binary messages).
The RINEX navigation files can be generated from OSP files having MID15 or MID8 messages. The problem if you use MID8 is that you would need several minutes of observation data to collect the calendar for all satellites. By the contrary MID15 provides immediately the current calendar in the receiver.
Nevertheless, I working now in the RXtoOSP and SynchroRX versions for Linux and I expect to provide you in few days at least an estimate of when it would be available a workable versions. The rest of the commands have been compiled without major problems.

**Comment by neslo** [comment]
thanks for all the details. Very helpful.

And sounds great that you have started porting the code

btw it sounds like i will be able to do with mid 8 since since time is not an issue.

**Comment by neslo** [comment]
I will add my current findings here such that it might assist you in implementing the low level stuff.

I have been logging data with both gpspipe (-R switch dumps the raw data) and gpscat on the raspberry.

I have then gone to a win machine for the post processing. I was able to generate an OSP file (PacketToOSP.exe,  v 1) with the data I had logged via gpspipe but no success with gpscat.  

I then ran OSPToTXT.exe (v1) on the OSP data and I was able to generate output that looked like the text file from the data folder. 

I then ran OSPToRinex.exe (v1 and default setting) but that just generated an empty Rinex header. So i am not sure it is because of the missing mid 15 messages or the OSP data I generated is corrupt.

**Comment by fcancillo** [comment]
Sorry again for the delay in my answer.
With regard to your questions, the only solution I have is to analyze the data you collected. May be you can send me the inputs you used in the PacketToOSP. Me direct addres is fcancillo@aeit.es
By the other side, I compiled the version for Linux of the programs, and they execute without problems, except the SynchroRX. I am working on it.

**Comment by neslo** [comment]
No worries at all  Francisco. I am just happy that you have spent some time on this. So just take your time.

Sounds great that you have come that far. Since it is no problem compiling it on Linux I am happy to try and debug my file and let you know what i have got and free you up to look at the remaining file

Have you got a project or just make files? (if it is a project would you be able to upload what you have got unless you prefer to wait til it is all done)

Otherwise I am also happy to send you a sample file

**Comment by fcancillo** [comment]
On Windows I am using Visual Studio. On Linux (Ubuntu) Eclipse.

**Comment by neslo** [comment]
Thanks for the details

**Comment by fcancillo** [comment]
I have just uploaded V2.1, including Linux (Ubuntu) code and commands.
I was unable to upload doc directory, but there are few changes w.r.t. the previous version.
Let me know any comment you could have.

**Comment by fcancillo** [comment]
Now the new doc is uploaded.

**Comment by neslo** [comment]
Thanks heaps  Francisco

I will let you know how i go
